FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_BASE_PATH=/
ARG STUDIO_BASE_PATH=/
ARG VITE_AI_GATEWAY_BASE_URL=
ARG VITE_AI_GATEWAY_MODEL_BASE_URL=
ARG VITE_AI_IMAGE_ROUTE=auto
ARG VITE_AI_RESPONSES_MODEL=gpt-5.5
ARG VITE_AI_RESPONSES_PARTIAL_IMAGES=2
ARG VITE_AI_PROMPT_OPTIMIZER_MODEL=
ARG VITE_AI_GATEWAY_LOGIN_URL=
ARG VITE_SUB2API_BASE_URL=
ARG VITE_SUB2API_GATEWAY_BASE_URL=
ARG VITE_SUB2API_IMAGE_ROUTE=auto
ARG VITE_SUB2API_RESPONSES_MODEL=gpt-5.5
ARG VITE_SUB2API_RESPONSES_PARTIAL_IMAGES=2
ARG VITE_SUB2API_PROMPT_OPTIMIZER_MODEL=
ARG VITE_SUB2API_LOGIN_URL=
ARG VITE_STUDIO_HISTORY_BASE_URL=
ARG VITE_STUDIO_BACK_URL=/
ARG VITE_STUDIO_LIBRARY_AUTH_REQUIRED=false
ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV STUDIO_BASE_PATH=$STUDIO_BASE_PATH
ENV VITE_AI_GATEWAY_BASE_URL=$VITE_AI_GATEWAY_BASE_URL
ENV VITE_AI_GATEWAY_MODEL_BASE_URL=$VITE_AI_GATEWAY_MODEL_BASE_URL
ENV VITE_AI_IMAGE_ROUTE=$VITE_AI_IMAGE_ROUTE
ENV VITE_AI_RESPONSES_MODEL=$VITE_AI_RESPONSES_MODEL
ENV VITE_AI_RESPONSES_PARTIAL_IMAGES=$VITE_AI_RESPONSES_PARTIAL_IMAGES
ENV VITE_AI_PROMPT_OPTIMIZER_MODEL=$VITE_AI_PROMPT_OPTIMIZER_MODEL
ENV VITE_AI_GATEWAY_LOGIN_URL=$VITE_AI_GATEWAY_LOGIN_URL
ENV VITE_SUB2API_BASE_URL=$VITE_SUB2API_BASE_URL
ENV VITE_SUB2API_GATEWAY_BASE_URL=$VITE_SUB2API_GATEWAY_BASE_URL
ENV VITE_SUB2API_IMAGE_ROUTE=$VITE_SUB2API_IMAGE_ROUTE
ENV VITE_SUB2API_RESPONSES_MODEL=$VITE_SUB2API_RESPONSES_MODEL
ENV VITE_SUB2API_RESPONSES_PARTIAL_IMAGES=$VITE_SUB2API_RESPONSES_PARTIAL_IMAGES
ENV VITE_SUB2API_PROMPT_OPTIMIZER_MODEL=$VITE_SUB2API_PROMPT_OPTIMIZER_MODEL
ENV VITE_SUB2API_LOGIN_URL=$VITE_SUB2API_LOGIN_URL
ENV VITE_STUDIO_HISTORY_BASE_URL=$VITE_STUDIO_HISTORY_BASE_URL
ENV VITE_STUDIO_BACK_URL=$VITE_STUDIO_BACK_URL
ENV VITE_STUDIO_LIBRARY_AUTH_REQUIRED=$VITE_STUDIO_LIBRARY_AUTH_REQUIRED
RUN npm run build

FROM nginx:1.27-alpine AS web

COPY deploy/docker-nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

FROM node:22-alpine AS history

WORKDIR /app

ENV NODE_ENV=production
ENV STUDIO_HISTORY_HOST=0.0.0.0
ENV STUDIO_HISTORY_PORT=8787
ENV STUDIO_DATA_DIR=/data
ENV STUDIO_LIBRARY_DIR=/app/library
ENV STUDIO_LIBRARY_ASSET_DIR=/app/library/image-library

COPY scripts/image-sub2api-studio-history-service.mjs ./scripts/image-sub2api-studio-history-service.mjs
COPY scripts/image-agent-studio-history-service.mjs ./scripts/image-agent-studio-history-service.mjs
COPY public ./library

RUN mkdir -p /data /app/library/image-library \
  && chown -R node:node /data /app

USER node

VOLUME ["/data"]
EXPOSE 8787

CMD ["node", "scripts/image-agent-studio-history-service.mjs"]
